### ISSUE TITLE
Disable automatic device switching if user doesn't follow the system default device

### ISSUE THREAD

**Issue by ChunMinChang** [mozilla/cubeb-coreaudio-rs#150]
To unblock [BMO 1735201](https://bugzilla.mozilla.org/show_bug.cgi?id=1735201) and [BMO 1238038](https://bugzilla.mozilla.org/show_bug.cgi?id=1238038), [`CUBEB_STREAM_PREF_DISABLE_DEVICE_SWITCHING`](https://github.com/mozilla/cubeb/blob/f79e0cf9f0620fe810b5ab034df698376197f444/include/cubeb/cubeb.h#L235) needs to be implemented in this crate.

**Comment by ChunMinChang** [comment]
We should fix #149 first. Then the code would be simpler I guess.

**Comment by ChunMinChang** [comment]
Instead of adding a pref for cubeb, I think it would be better to "disable automatic device switching" by default unless users ask to follow the system default device. That should be the default behavior in Firefox.

**Comment by padenot** [comment]
Then we need to add a flag to ask to follow default devices, right ?

**Comment by ChunMinChang** [comment]
> Then we need to add a flag to ask to follow default devices, right ?

I think using `nullptr` for the device id, as what we do now, is enough.

**Comment by ChunMinChang** [comment]
Resolved by #154
