### ISSUE TITLE
Inadvertent low-pass filter at ~11kHz

### ISSUE THREAD

**Issue by mutexlox-signal** [mozilla/cubeb-coreaudio-rs#242]
### Steps to reproduce:

1. Find a device (possibly that uses Float32Ne natively - e.g., built-in microphone on most macs, or 3.5 mm jacks)
2. Start a stream with it requesting S16NE format, and record output with blackhole
3. Play some audio into the microphone
4. Analyze the spectrum (in, e.g., audacity)
5. Observe that frequencies above roughly 11kHz are missing

The same thing seems to happen if you request Float32Ne as the stream format, and also I believe if the device natively uses s16.

Alternate steps with the convenience repo I set up (which assumes you have a `Blackhole 2ch` device set up)

1. Clone https://github.com/mutexlox-signal/test-coreaudio-rs
2. `cargo build`
3. Set your default input device to be the input under test
4. Start recording from the blackhole 2ch input
5. `cargo run`
6. Start playing something into the microphone
7. Analyze the spectrum (in, e.g., audacity)
8. Observe that frequencies above ~11kHz are missing

### Expected behavior:

Streams should not have a low-pass filter at ~11kHz.

### Actual behavior:

Streams have a low-pass filter at ~11kHz.

### Appendix

Recording with s16 input:
<img width="1510" alt="recording_s16_input" src="https://github.com/user-attachments/assets/904bf2a4-f969-44cf-9ddf-d277422215ce">

Source (also in https://github.com/mutexlox-signal/test-coreaudio-rs for convenience):

```rust
//! libcubeb api/function test. Records from the microphone and plays to the speaker.
extern crate cubeb;

use cubeb::MonoFrame;
use std::thread;
use std::time::Duration;

const SAMPLE_FREQUENCY: u32 = 48_000;
const STREAM_FORMAT: cubeb::SampleFormat = cubeb::SampleFormat::S16NE;

type Frame = MonoFrame<i16>;

use cubeb::Context;

fn main() {
    cubeb_core::set_logging(
        cubeb::LogLevel::Normal,
        Some(|s| {
            println!("{}", s.to_str().unwrap().trim());
        }),
    )
    .expect("log failed");
    let ctx = Context::init(Some(c"Cubeb recording example"), None)
        .expect("Failed to create cubeb context");

    println!("using backend {}", ctx.backend_id());

    let params = cubeb::StreamParamsBuilder::new()
        .format(STREAM_FORMAT)
        .rate(SAMPLE_FREQUENCY)
        .channels(1)
        .layout(cubeb::ChannelLayout::MONO)
        .prefs(cubeb_core::StreamPrefs::VOICE)
        .take();

    let device_id = ctx
        .enumerate_devices(cubeb::DeviceType::OUTPUT)
        .unwrap()
        .iter()
        .find(|d| d.friendly_name() == Some("BlackHole 2ch"))
        .unwrap()
        .devid();

    let mut builder = cubeb::StreamBuilder::<Frame>::new();
    builder
        .name("Cubeb recording (mono)")
        .output(device_id, &params)
        .default_input(&params)
        .latency(0x1000)
        .data_callback(move |input, output| {
            for (i, x) in input.iter().enumerate() {
                output[i] = *x
            }
            output.len() as isize
        })
        .state_callback(|state| {
            println!("stream {:?}", state);
        });

    let stream = builder.init(&ctx).expect("Failed to create cubeb stream");

    stream
        .set_input_processing_params(
            cubeb_core::InputProcessingParams::ECHO_CANCELLATION
                | cubeb_core::InputProcessingParams::NOISE_SUPPRESSION
                | cubeb_core::InputProcessingParams::AUTOMATIC_GAIN_CONTROL,
        )
        .expect("failed to set params");

    stream.start().unwrap();
    thread::sleep(Duration::from_millis(30000));
    stream.stop().unwrap();
}
```

**Comment by mutexlox-signal** [comment]
As a point of comparison, if I record the same track directly from the microphone in question via audacity, I get this spectrum:

<img width="1508" alt="Screenshot 2024-11-11 at 2 12 56 PM" src="https://github.com/user-attachments/assets/99da3891-4427-4692-913b-6a1875507ca0">

**Comment by mutexlox-signal** [comment]
It is possible, but I'm not sure, that if the native format of a device is 16-bit int (rather than 32-bit float) this does not reproduce.

**Comment by mutexlox-signal** [comment]
Possibly-relevant: the speex version in cubeb appears to be several years out of date. In particular, it seems to be missing https://github.com/xiph/speexdsp/commit/00d2e621c53bd5ca6dabd12f97d1224b3705645a, which **might** be relevant...

EDIT: manually pulling in that commit does not make a difference, unfortunately, but it might still be a good idea to update speex.

**Comment by kinetiknz** [comment]
Thanks for filing the bug.  I'm seeing similar behaviour here, including at the device's native sample rate so resampling is likely not the cause.  I'm suspicious of this being related to VPIO, but I'm not having much luck forcing VPIO off to confirm this.

@Pehrsons @ChunMinChang Any ideas about the cause of this?

**Comment by Pehrsons** [comment]
@mutexlox-signal does this reproduce also for a non-builtin device with CUBEB_STREAM_PREF_VOICE not set on the input stream?

**Comment by mutexlox-signal** [comment]
Unfortunately, it seems like when I disable voice mode on the device I have at hand I only get silence. Let me see if I can get a different device wired up.

**Comment by mutexlox-signal** [comment]
* When I play audio directly into a blackhole device, and read audio from that blackhole device, even with voice mode turned on the spectrum looks fine (and the audio sounds fine), going until 14kHz. Ideally we'd get until 20kHz, but 14 is good enough to sound subjectively better.
<img width="1493" alt="Screenshot 2024-11-12 at 10 02 52 AM" src="https://github.com/user-attachments/assets/3f121d10-a3a3-44b3-9bfa-3e6254065cfb">

* Even using a blackhole input, when not using voice and using a blackhole output, I still get silence... curious.

**Comment by mutexlox-signal** [comment]
(By "silence," I literally do mean silence -- the maximum input I see is 0 in my data callback without voice mode)

**Comment by mutexlox-signal** [comment]
To be more specific: I only seem to observe all 0s on the input side if my output side is a blackhole device; if I wire my physical headphones to be the output device, that works fine.

**Comment by mutexlox-signal** [comment]
Some interesting findings from system logs when running the program:

```
default	14:46:56.137365-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] value of property 48 'Client_Far_End_Voice_Input_Block' is MCpqAgBgAAA=
```

I'm not sure what this means, precisely. I don't see any documentation of `Client_Far_End_Voice_Input_Block` anywhere, nor am I sure what the base 64 string there is.

I also see a very suspicious set of lines:

```
default	14:46:56.143925-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (UL) content input 'mic' format is  1 ch,  44100 Hz, Float32
default	14:46:56.143963-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (UL) echo I/O block size is 240
default	14:46:56.144001-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (UL) echo I/O sample rate is 24000.000000
default	14:46:56.144043-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (UL) echo configuration is {".austrip":["Generic/V1/VPVX/unkn-unkn-misc-ulnk.austrip"],".dspg":"DSP/UL/uplink_echo.dspg",".propstrip":["DSP/UL/uplink_echo.propstrip"],".propstrip (override)":null}
default	14:46:56.144078-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (UL) echo input 'mic' format is  3 ch,  24000 Hz, Float32, deinterleaved
default	14:46:56.144112-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (UL) echo input 'mic_clip_data' format is  3 ch,  24000 Hz, Float32, deinterleaved
default	14:46:56.144145-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (UL) echo input 'ref' format is  2 ch,  24000 Hz, Float32, deinterleaved
default	14:46:56.144179-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (UL) echo output 'mic' format is  1 ch,  24000 Hz, Float32
```

and

```
default	14:46:56.145447-0800	test-coreaudio-rs	[vp::vx::Voice_Processor:0x13d009600] (DL) voice I/O sample rate is 32000.000000
```

**Comment by mutexlox-signal** [comment]
Full system log from that: [console output voice processing.txt](https://github.com/user-attachments/files/17723773/console.output.voice.processing.txt)

**Comment by mutexlox-signal** [comment]
FWIW, this is not limited to specifics of the test program.

The equivalent test in firefox 132.0.2 (aarch64) -- namely, loading https://webrtc.github.io/samples/src/content/devices/input-output/, setting input to the external mic and output to the blackhole device -- shows a remarkably similar spectrum:

<img width="1512" alt="Screenshot 2024-11-12 at 4 34 09 PM" src="https://github.com/user-attachments/assets/bd2e0f85-c4f2-4eee-9c70-a0cfde6d3adb">

**Comment by Pehrsons** [comment]
If the processing graph runs at 24k that would explain a low-pass filter effect at ~12k wouldn't it?

**Comment by mutexlox-signal** [comment]
Possibly, it depends on what exactly the echo cancellation is doing. I guess if that's the case this would be an apple bug? (Or possibly some configuration knob we can tweak in setting up the VPIO unit?)

**Comment by mutexlox-signal** [comment]
FWIW, chrome does not show this behavior; here's the spectrum for the same test as in https://github.com/mozilla/cubeb-coreaudio-rs/issues/242#issuecomment-2472024021

<img width="1506" alt="Screenshot 2024-11-13 at 10 02 00 AM" src="https://github.com/user-attachments/assets/723cb290-1ba7-468c-94fd-2bbe864a823c">

**Comment by mutexlox-signal** [comment]
Safari, on the other hand, behaves identically to Firefox, cutting off at 11kHz...

<img width="1507" alt="Screenshot 2024-11-13 at 10 44 50 AM" src="https://github.com/user-attachments/assets/98568de6-c342-4f7e-96cc-28c367144e3e">

**Comment by mutexlox-signal** [comment]
Confirmed with @Pehrsons that this issue does not occur for affected devices if VPIO is off.

**Comment by Pehrsons** [comment]
Thanks for that confirmation. I think for video calling use cases, where processing is requested, this isn't surprising.
The problem here is the force list leaving you with no way to escape VPIO for those devices on the list. It makes some sense for gecko as a means to avoid the case where a site requests one stream with processing and one without (with 2 VPIO units on a builtin device, the one with processing sounds fine but the one in bypass mode has very low gain). In gecko I plan to fix this by disallowing some combinations of processing params on a per-stream basis. As a stop gap measure to let other clients avoid the forcelist I plan to add a cfg flag for *enabling* the force list, so it is disabled by default.

**Comment by mutexlox-signal** [comment]
I have filed FB15839727 with Apple for the echo cancellation sample rate issue.
