### ISSUE TITLE
Make mixer become an independent crate

### ISSUE THREAD

**Issue by ChunMinChang** [mozilla/cubeb-coreaudio-rs#35]
The mixer crate is introduced in #23 to solve the [BMO 1468381][bmo1468381]. The new mixer is able to mix audio from any input layout to any output layout. 

The [BMO 1368938][bmo1368938]: mixer only support pre-defined layout on Windows, is probably the same problem of [BMO 1468381][bmo1468381] so it is likely to be solved by adopting the new mixer on Windows. 

Therefore, it's better to make the new mixer crate as an independent crate that can be used to other platforms and make it as a successor of [cubeb_mixer][cubeb_mixer].

[bmo1468381]: https://bugzilla.mozilla.org/show_bug.cgi?id=1468381
[bmo1368938]: https://bugzilla.mozilla.org/show_bug.cgi?id=1368938
[cubeb_mixer]: https://github.com/kinetiknz/cubeb/blob/aa636017aca8f79ebc95fb9f03b9333eaf9fd8fc/src/cubeb_mixer.h

**Comment by ChunMinChang** [comment]
The mixer crate is moved to https://github.com/ChunMinChang/audio-mixer now

**Comment by ChunMinChang** [comment]
Soved by #37

**Comment by Squall-Leonhart** [comment]
Sad news Chun, looks like this broke the rear channels on XFI with enhancements turned on.

**Comment by ChunMinChang** [comment]
> Sad news Chun, looks like this broke the rear channels on XFI with enhancements turned on.

I don't think I understand the reasoning. Could you describe why you suspect this update is the cause?

It seems the problem issued in mozilla/cubeb#661 is on Windows, while [the mixer crate](https://github.com/mozilla/audio-mixer) is only used on macOS now. The mixer-crate hasn't been imported into Windows yet.
