### ISSUE TITLE
Have an easy way to turn on the `cubeb_log!`

### ISSUE THREAD

**Issue by ChunMinChang** [mozilla/cubeb-coreaudio-rs#70]
The `cubeb_log!` won't print anything now. We should have a way to turn on those logs so it can help debugging.

**Comment by ChunMinChang** [comment]
https://github.com/ChunMinChang/cubeb-coreaudio-rs/commit/323550d21b8644731c108fc4e6ac46d514f9c235 could work in *Rust Nightly* with`c_variadic` feature. 

Another workaround https://github.com/ChunMinChang/cubeb-coreaudio-rs/commit/9af97621f7af5a90630404fd30d48759761cba08 is using `cc` to build a custom log function in *C*. 
Otherwise we need to wait until https://github.com/rust-lang/rust/issues/44930 is fixed.

**Comment by mutexlox-signal** [comment]
IIUC https://github.com/mozilla/cubeb-rs/pull/98 should fix this
